version: "3.8"
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root
      # root userに外部からのアクセス権付与
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Tokyo